In [112]:
#imports and scraping raw data from site
#df is the actual betting line
#df2 has other info, mostly using to get player id to name dict

import pandas as pd
import datetime as dt
import re
from unidecode import unidecode
from betting_functions import get_url_json

In [113]:
dog_props_url = 'https://api.underdogfantasy.com/beta/v3/over_under_lines'
data = get_url_json(dog_props_url)

In [114]:
data.keys()

dict_keys(['appearances', 'games', 'over_under_lines', 'players', 'solo_games'])

In [115]:
df = pd.json_normalize(list(data.values()))
df.index = data.keys()
new = df.T['over_under_lines'].values
lines = pd.json_normalize(new)
lines.sample(2)

,id,live_event,live_event_stat,options,over_under_id,rank,stat_value,status,over_under.id,over_under.appearance_stat.id,over_under.appearance_stat.appearance_id,over_under.appearance_stat.display_stat,over_under.appearance_stat.graded_by,over_under.appearance_stat.pickem_stat_id,over_under.appearance_stat.stat,over_under.boost,over_under.scoring_type_id,over_under.title
3055,bd2e9c87-4bc9-4f5e-a7ec-d80c34b491b0,False,None,[{'id': 'fded897f-700e-46d4-8709-3c7bf5cf9bb9'...,23d649b1-0cf3-422a-9988-0dd836dfa581,25190053,2.0,active,23d649b1-0cf3-422a-9988-0dd836dfa581,178affe2-cbab-4fdb-a810-a9d1f79b79d4,ce0d15b3-1fd3-48e7-b923-4a0b826e6afe,Kills in Maps 1+2+3,high_score,58928a02-7fb5-4f3e-a004-74a205514a66,kills_in_maps_1_2_3,None,None,LoL: Garank Kills in Maps 1+2+3 O/U
2952,e786ba23-b570-41fd-9b4c-6072bcbc4035,False,None,[{'id': '81121dbb-1fbe-4597-98b9-a089f6f0db87'...,58f751be-029b-4b75-ae80-050b608a347d,25189129,5.0,active,58f751be-029b-4b75-ae80-050b608a347d,6b918670-fdea-4907-991f-ab7eac88b635,d6bc0db0-7ea5-4f72-ad6e-61a8fcd22edf,Assists on Map 2,high_score,da6d78ce-4837-4bd6-9257-8bde0eb93c74,assists_in_map_2,None,None,LoL: Flawed Assists on Map 2 O/U

In [116]:
test =  pd.json_normalize(df.T['players'])
player_df = test.copy(deep=True)
player_df = player_df[['id','first_name', 'last_name',
       'sport_id','team_id']]
player_df = player_df.dropna()#

player_df.loc[player_df.sport_id=='ESPORTS']
x = player_df[player_df.sport_id=='ESPORTS']
p2esport = x[['last_name','first_name']].to_dict('split')
p2esport = dict(p2esport['data'])

In [117]:
test =  pd.json_normalize(df.T['players'])
player_df = test.copy(deep=True)
player_df = player_df[['id','first_name', 'last_name',
       'sport_id','team_id']]
player_df = player_df.dropna()
player_df.loc[player_df['sport_id'] != 'ESPORTS', 'full_name'] = player_df['first_name']+' ' + player_df['last_name']
player_df.loc[player_df['sport_id'] == 'ESPORTS', 'full_name'] = player_df['last_name']
#player_df['full_name'] = player_df['first_name']+' ' + player_df['last_name']
player_df = player_df[['full_name','sport_id','team_id']]
p2l = player_df[['full_name','sport_id']].to_dict('split')
p2tm = player_df[['full_name','team_id']].to_dict('split')
temp = p2l['data']
temp2 = p2tm['data']
p2l = dict(temp)
p2tm = dict(temp2)

In [118]:
player_df

,full_name,sport_id,team_id
0,Joel Embiid,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
1,Tyrese Maxey,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
2,Tobias Harris,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
3,Kelly Oubre Jr.,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
4,De'Anthony Melton,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
...,...,...,...
1004,J. Harden + R. Westbrook,NBACOMBOS,b231abcd-c8eb-4f5c-b5a9-70f3b97c8b3e
1005,K. Hayes + I. Stewart,NBACOMBOS,81961de1-1a9c-4f87-a145-668a926bf026
1006,P. Washington + M. Williams,NBACOMBOS,cb8b8955-a786-4bb3-8fd0-5b438e61d3d1
1007,T. Harris + D. Melton,NBACOMBOS,19ecbc41-1201-478c-9937-c339c3963b69
1010,S. White + R. Keyton,CFBCOMBOS,47d97fab-ff83-4b75-996a-0643e75e4a21

In [119]:
player_df.sport_id.unique()

array(['NBA', 'NFL', 'CFB', 'CBB', 'NHL', 'FIFA', 'ESPORTS', 'BASKETBALL',
       'CFL', 'NFLCOMBO', 'NBACOMBOS', 'CFBCOMBOS'], dtype=object)

In [120]:
first2 = player_df['full_name'].apply(lambda x: ' '.join(x.split()[0:2]))
names = pd.DataFrame((first2,player_df.full_name))
names = names.T
names.columns=['first2','fullname']
names.loc[names.first2=='Jazz Chisholm']
first2full = names.to_dict('split')
first2full = dict(first2full['data'])

In [121]:
games = pd.json_normalize(df.T['games'].values).dropna(how='all')
#games = games.loc[games['sport_id']=='NBA']
games.tail(3)

,id,away_team_id,away_team_score,home_team_id,home_team_score,match_progress,period,scheduled_at,season_type,sport_id,status,title,type,year
96,57742.0,7a9d17b6-38c3-402a-9f78-4626e1db104d,0.0,fd67152d-cfb5-47d5-8113-6a37da8a73da,0.0,Fri 03:00pm,0.0,2023-11-10T20:00:00Z,regular,BASKETBALL,scheduled,Lyon-Villeurbanne @ Monaco,Game,2023.0
97,57684.0,cb31c28e-6b10-459b-a8e8-123f37715b0d,0.0,2822c78a-243c-4365-ab0f-bfef88cbac45,0.0,Sat 03:00pm,0.0,2023-11-11T20:00:00Z,regular,CFL,scheduled,MTL @ TOR,Game,2023.0
98,57685.0,c3cb471d-2cbd-4cb4-9d57-c8ef7b7d380b,0.0,643ebde6-4db7-48c1-844d-8aa5f8482746,0.0,Sat 06:30pm,0.0,2023-11-11T23:30:00Z,regular,CFL,scheduled,BC @ WPG,Game,2023.0

In [122]:
def to_central(date_str):
    x = pd.to_datetime(date_str)
    x = x.tz_convert('US/Central')
    return str(x.date())
to_central('2023-05-20T00:40:00Z')

'2023-05-19'

In [123]:
games.scheduled_at = games.scheduled_at.apply(to_central)

In [124]:
#grabbing team names from match title
matchup = games['title']
home = []
away = []
for i in matchup:
    temp = re.split(' @ |, |vs.',i)
    home.append(temp[0])
    away.append(temp[1])
#fixing esports team names
for i in range(len(home)):
    home[i] = home[i].split(': ')[-1]
    
for i in range(len(away)):
    away[i] = away[i].split(': ')[-1]

matchup = pd.DataFrame((away,home,games.away_team_id,games.home_team_id)).T
matchup.columns = ['Home', 'Away','away_id','home_id']
dates = games['scheduled_at'].values
#temp = []
#for i in dates:
#    temp.append(i.split('T')[0])
matchup['Date'] = dates
id2tm =  matchup[['home_id','Home']].to_dict('split')
id2tmaway =  matchup[['away_id','Away']].to_dict('split')
id2tm = dict(id2tm['data'])
id2tmaway = dict(id2tmaway['data'])
id2tm.update(id2tmaway)

In [125]:
games

,id,away_team_id,away_team_score,home_team_id,home_team_score,match_progress,period,scheduled_at,season_type,sport_id,status,title,type,year
0,52476.0,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72,0.0,47f5f48d-3d14-46f3-b6dc-1e7b4dfb1e69,0.0,Fri 07:00pm,0.0,2023-11-10,regular,NBA,scheduled,PHI @ DET,Game,2023.0
1,52475.0,11cfe154-8ba6-4c22-be8f-2365656fb4da,0.0,402685bd-a73c-4eb1-8c0f-55debd622215,0.0,Fri 07:00pm,0.0,2023-11-10,regular,NBA,scheduled,CHA @ WAS,Game,2023.0
2,52477.0,a34e5fa9-e4aa-4195-98bf-05710d97347d,0.0,8f5852b6-c8dc-4cce-980a-eab09b28919a,0.0,Fri 07:30pm,0.0,2023-11-10,regular,NBA,scheduled,BKN @ BOS,Game,2023.0
3,52478.0,f15a9fdd-f178-42ff-aab6-63b9198a34c8,0.0,fee4a894-1970-402a-873b-8faea88f4ec9,0.0,Fri 08:00pm,0.0,2023-11-10,regular,NBA,scheduled,MIN @ SAS,Game,2023.0
4,52480.0,ade6b8fc-178f-4e7e-b43d-aa853bea0f3a,0.0,56a5d8c8-eb72-47db-9e93-5b24d8f5443a,0.0,Fri 08:00pm,0.0,2023-11-10,regular,NBA,scheduled,UTA @ MEM,Game,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,57740.0,4bb9808b-d679-4a63-9755-f1e89861e726,0.0,889a9c83-01b9-4ee9-a00b-04c7004c2033,0.0,Fri 02:00pm,0.0,2023-11-10,regular,BASKETBALL,scheduled,Panathinaikos @ Alba Berlin,Game,2023.0
95,57741.0,cccce565-c662-4118-90d8-700bd3da5b70,0.0,c2392e23-8b66-4062-8860-48021a586dc8,0.0,Fri 02:30pm,0.0,2023-11-10,regular,BASKETBALL,scheduled,Crvena Zvezda @ FC Barcelona,Game,2023.0
96,57742.0,7a9d17b6-38c3-402a-9f78-4626e1db104d,0.0,fd67152d-cfb5-47d5-8113-6a37da8a73da,0.0,Fri 03:00pm,0.0,2023-11-10,regular,BASKETBALL,scheduled,Lyon-Villeurbanne @ Monaco,Game,2023.0
97,57684.0,cb31c28e-6b10-459b-a8e8-123f37715b0d,0.0,2822c78a-243c-4365-ab0f-bfef88cbac45,0.0,Sat 03:00pm,0.0,2023-11-11,regular,CFL,scheduled,MTL @ TOR,Game,2023.0
98,57685.0,c3cb471d-2cbd-4cb4-9d57-c8ef7b7d380b,0.0,643ebde6-4db7-48c1-844d-8aa5f8482746,0.0,Sat 06:30pm,0.0,2023-11-11,regular,CFL,scheduled,BC @ WPG,Game,2023.0

In [126]:
id2tm

{'47f5f48d-3d14-46f3-b6dc-1e7b4dfb1e69': 'DET',
 '402685bd-a73c-4eb1-8c0f-55debd622215': 'WAS',
 '8f5852b6-c8dc-4cce-980a-eab09b28919a': 'BOS',
 'fee4a894-1970-402a-873b-8faea88f4ec9': 'SAS',
 '56a5d8c8-eb72-47db-9e93-5b24d8f5443a': 'MEM',
 '2c204562-627d-4fbe-b9ba-24a8bbf87463': 'DAL',
 'f98f3baa-ad03-4188-9e8a-0cb52e1b900e': 'PHX',
 'f97fdf6e-8328-4000-ba49-0b2ce0beae71': 'SAC',
 'ef876de9-81ac-5e60-af6e-0ca1700f3a51': 'NE',
 'b49b653c-dc7c-516e-b1c2-da1b30d1b1a6': 'JAX',
 '01bfe9d5-f671-57ed-aa60-249fcca9267c': 'BAL',
 'ab235cf0-a041-5d36-8241-90a90f0dcb5e': 'CIN',
 '5af1e185-627e-5345-851d-3c65c5b66614': 'MIN',
 'ecc8eb1b-f714-57a6-bcf3-b183dd6c12a8': 'PIT',
 '1a20f1da-c502-5224-9c4a-bc363174cd21': 'TB',
 'c7b497d4-18b6-522b-abaa-e5c3d24bc021': 'LAC',
 '8459772c-695a-5890-afa1-7ec38da17201': 'ARI',
 '31631011-5902-52f6-ba01-c4c8d8eb3fd9': 'SEA',
 '26e67e06-664e-50a6-ad7b-c102705fde8b': 'DAL',
 '5ce78c37-b02c-52da-9e4f-fcd65b6ccb76': 'LV',
 '0719b253-43db-532e-8b5c-6c12c6c3f951': 'BUF',
 '9f3952f8-b2c5-4531-bcd3-1dbd970250ff': 'SMU',
 '25cb4c5b-31af-4aa5-b200-ebf28a676cea': 'PSU',
 '7927577f-9eb8-43bb-935d-b4a545e9e986': 'KEN',
 '780d1c04-6749-4b79-9c64-aa35a08146ab': 'KAN',
 '715ba923-890f-44a2-8c82-1c9b922232d3': 'CLE',
 '6abd4f5d-9165-40f0-af8e-46adef7cfee6': 'SC',
 '7de51156-7fe0-4c86-ae4c-09aacf7b41d6': 'NEB',
 '9e7a6e95-bea0-4bf8-86f3-9b70b807c704': 'ILL',
 'fc1177f8-beed-4170-acf5-fe669bb4795a': 'COL',
 '2503e37c-0856-4d17-8b52-975d1f5d66e9': 'MIZ',
 '70933dd1-8440-44ca-a578-4062c8789d70': 'FSU',
 'ec10d4ff-d8d0-4c8b-b493-a855479db6e1': 'UCF',
 'a0ed56d4-aded-4744-98a7-2b4adb24ff70': 'WAS',
 '68fb7ef8-0d50-405e-a6a9-5817d95e3311': 'PUR',
 '73d236ba-b44d-44e3-a121-4c3884c31bd9': 'IOW',
 '421f09b9-43c3-422a-ac60-7ef2d69f326b': 'WIS',
 'c737722d-3e6b-43d0-9be7-b1885eaa795e': 'ARK',
 '66a40421-4792-480a-8d42-148d9ad5bc59': 'CAL',
 '851b1705-a35b-42d5-bf89-ccc0ebb7565b': 'ORS',
 'b7eddd06-91a2-47b0-8813-8b1ef4ddb287': 'UGA',
 '98c5d11a-1488-4d98-9110-80f813491bd2': 'OKL',
 'b7e00343-267d-45f9-8fcb-9574a932ee64': 'TCU',
 '86c6882a-d54d-41bb-bc69-7d5a063b9c8f': 'NC',
 '5bf5a4b7-bb12-4adf-a507-60eeb9bda0d8': 'UCLA',
 'fcfcfa20-fca3-4493-b662-dcf04bb66551': 'BYU',
 '365198b9-4772-4198-b1ab-614c5b24ee73': 'ORE',
 '66c9b98d-7f90-4b7e-bf4a-e062b04c70cc': 'MD',
 '236d104a-b1e6-4d56-8ceb-5b9f25a3f3a3': 'NW',
 'fdeff141-96cb-48ba-bca3-369645a49c7e': 'OSU',
 '775c5d55-8e56-4502-97c1-775041fdfab2': 'PUR',
 '8958a1f2-a8c5-4e13-a26a-fdefc0b4f47f': 'RUTG',
 '0490b88b-14a9-4db0-bedb-791a7e1627be': 'WIS',
 'dc5264a9-6ed2-4a86-aeac-a8051c2e6c6d': 'TOR',
 '6ffb5a76-ee62-4902-a5aa-5af2859fb4b5': 'BUF',
 'f6045934-74fa-4952-8cc7-4de08c851a8b': 'NJ',
 'e1a07af8-365d-4261-8b9b-3ccbc99e5e21': 'FLA',
 '9507b4a6-eea0-447d-af29-6391def14b20': 'ANA',
 '21c32c27-2668-4d04-a209-497292923e36': 'VGK',
 'ac97d2c0-e1d3-4a82-9612-9693c6d6b284': 'Sassuolo',
 'cb439308-00d0-4401-8b0c-21c3252b608b': 'Borussia Mönchengladbach',
 '93d56a26-ffee-421c-a051-475d06b00ddc': 'Genoa',
 '8c58e003-c8ca-414e-a0e0-35d161cca360': 'Athletic Bilbao',
 '997e5af0-f738-454b-8253-06f2272398c0': 'Montpellier',
 '87cad6d7-888f-4494-a3de-5d6c1c469df8': 'Seattle Sounders',
 'ffe2ab78-bcf8-42ce-a91d-d2409a035cb7': 'Wolves',
 '7f062902-0c16-4be1-9af7-46e802cbc9b1': 'VfB Stuttgart',
 '24487a12-61c5-4eb3-962e-e7f7d18a55fd': 'FC Augsburg',
 '4247617e-60da-4b5c-bdbe-4ee3e1232539': 'SV Darmstadt',
 'fa6633d9-2de4-42d1-927e-470f9eb4299d': 'Arsenal',
 'e5c38924-be02-4d77-98d6-06324d759a74': 'Manchester United',
 'afaf8490-6eab-42db-9807-db3ce3a4b18e': 'Crystal Palace',
 'b044d1d4-c59c-4094-bdc4-976a119f4064': 'Reims',
 '9cbbf45a-f622-4520-a8d4-79237e5f8b11': 'Bournemouth',
 'dbcb8324-600b-412b-b2d6-6e52b3310f6e': ' Weibo Gaming',
 'b009004c-0127-436c-8a75-7c2e103e1151': ' T1',
 'c6e05954-0873-447a-9577-d295c17b7528': ' Leviatan',
 'a8397a51-6561-4c11-9612-ec8c509bfd55': ' Cloud9',
 '501eaaff-16cc-4df5-8f76-f0f82f3b136c': ' UCAM Esports Club',
 'e477a275-95e2-4cee-b757-ac78bf8f489f': ' Ovation eSports',
 '5997576c-27a3-4ffc-af80-92b7bd998ef9': ' GoNext',
 '32bc491a-d3f3-4865-b4c6-53351edb01f6': ' Project G',
 'ba83efbd-2e6f-42c8-b30a-072999f2e4ff': ' Badass',
 '4caf77a7-0158-4f59-9749-797902b2bfbc': ' Party Astronauts',
 '3aab7726-0fad-4d90-aebc-eb6c59eb1e9c': ' MOUZ',
 '4060d429-d1d6-4218-b0ea-fe0fd6141a98': " Cobro'sCobros",
 '2c2a9d83-4e62-4208-97f6-9ecc356c15f3': ' Sunday School',
 '19f56708-b5f4-4e8f-94c5-7193cbf385f1': ' Mindfreak ',
 'ca5046c3-0868-4562-a10f-a69bfe37cf44': ' K2G',
 'db912eb7-6b41-40e4-9f36-db92b437d33b': ' Ninjas in Pyjamas',
 '4df81f2d-c4bf-4463-a6cd-4bcb61a4df06': ' KOI Academy',
 '5e0341fa-b6e1-4718-a91d-cf1e5e993c03': ' A One Man Army',
 '15e82656-bb76-4985-91f7-c68fd7408d54': ' Mythic Esports',
 '4fa3580f-22bf-47c8-98f4-5c44cf56be50': ' Orbit Anonymo',
 '889a9c83-01b9-4ee9-a00b-04c7004c2033': 'Alba Berlin',
 'c2392e23-8b66-4062-8860-48021a586dc8': 'FC Barcelona',
 'fd67152d-cfb5-47d5-8113-6a37da8a73da': 'Monaco',
 '2822c78a-243c-4365-ab0f-bfef88cbac45': 'TOR',
 '643ebde6-4db7-48c1-844d-8aa5f8482746': 'WPG',
 '4dd50e92-0a87-4a6a-bb5d-31c36d88ae72': 'PHI',
 '11cfe154-8ba6-4c22-be8f-2365656fb4da': 'CHA',
 'a34e5fa9-e4aa-4195-98bf-05710d97347d': 'BKN',
 'f15a9fdd-f178-42ff-aab6-63b9198a34c8': 'MIN',
 'ade6b8fc-178f-4e7e-b43d-aa853bea0f3a': 'UTA',
 'bd4b60cd-5adb-4cc6-8e8a-97084501f386': 'LAC',
 '97616c91-0509-42f8-99f3-04f3856a6377': 'LAL',
 'f6d5eae0-8f7d-4c63-85b3-b06298f3852c': 'OKC',
 'f11f1cf1-9933-5203-8181-95020ee64399': 'IND',
 '7161e62b-de20-56e2-a300-0dc23637faaa': 'SF',
 '338ae7df-02ad-5a94-9767-60f511bd55e1': 'CLE',
 '4ab08caa-b79d-598e-82ef-0906a60d2a89': 'HOU',
 '530518ed-91db-57c4-9077-27cc0dd9a293': 'NO',
 'a2fadaac-562f-5a7e-bd63-6d88d90c1ac4': 'GB',
 'f96aa8db-21c2-5b86-b49d-7e64b4eda61d': 'TEN',
 'a8980eb6-327f-5bc5-abf9-de1e944b566d': 'DET',
 '8699a914-7d44-5a36-b7a6-2063d3ea761f': 'ATL',
 'a6d8dc19-daaf-5798-a8f2-df7f9fc9eecd': 'WAS',
 'd40a4380-49a6-5b5f-ab7d-f5393787ed12': 'NYG',
 '516ded41-e882-5175-9a00-d0b4c028eb74': 'NYJ',
 '7b3b21be-a209-5dee-a3f7-3fae61f52a1e': 'DEN',
 '4a4ffae0-a256-4d9c-9721-43c9c471600d': 'NTX',
 '85898164-93a3-4083-ae1a-770c6702c85d': 'MICH',
 'f418e3f8-7b02-4f74-b5fa-309b191bb94e': 'BAMA',
 'd8c72ef1-b248-4e6a-84d0-beb9b5f99392': 'TT',
 '28b72898-1e9d-42fe-a4cf-f70a6959ec44': 'GT',
 '2a3c4a9e-dd43-461c-9c5c-4cea282e34f1': 'VAN',
 'ade1af85-07c7-46ce-acd4-7c969bb33845': 'MAR',
 '90e5da89-02d6-4bdb-a1ac-f98448075412': 'IU',
 '9e85ca91-d87e-4a78-8726-8482c731e48e': 'ARI',
 '0bda1a74-f5ac-4bab-8de7-9216167d9858': 'TEN',
 '375218f9-fb9f-4ffe-af00-e6d981349703': 'MFL',
 'a2f0fef9-70c3-4b0c-8b8b-fb17fca73e26': 'OKS',
 '1e12318e-b847-4746-94ca-41d2d887e7fc': 'UTH',
 '023d5b6e-4fe3-4c79-96fc-7fa24dc9c9b7': 'MIN',
 'a961f89f-4680-4492-aba5-da79808b0cd8': 'RUT',
 '2411941a-559c-4ef4-a976-cfd9164fbda5': 'NW',
 'c38c29de-1e7b-493a-b0d7-eaddb23c1ab5': 'AUB',
 '05115f6d-6c71-4d87-b7ab-78beee434af5': 'WST',
 'abfd3adb-f738-40cc-93d4-8ed39e730d65': 'STA',
 'ef3fe165-79cb-467a-88bb-966d5d1cce4c': 'MIS',
 '516258e6-cbbb-4d5f-81e7-98ec9375027c': 'WVU',
 'a38d0932-4c63-4c04-8351-34565d0045ed': 'TEX',
 'e29bb91e-2dc4-412e-9f35-217a6ad8c27d': 'DUK',
 '4318d306-1710-40ed-b9dd-81c546b1d371': 'ASU',
 'cbb14968-1028-4c42-8189-41ac9d2150e5': 'ISU',
 '8c5f0dff-252e-4946-9266-2f0a927ad56b': 'USC',
 '10cf99e8-ac3a-47a2-a488-a5545a1c5e37': 'DAV',
 '9ad0cc9c-0b0a-454e-9fd8-01a50220e0d1': 'DAY',
 '94005449-5b40-4085-a8af-4e971bd243a4': 'TXAM',
 '4d574289-7d4e-4181-b9be-8fededd94aa7': 'MORE',
 '6b7ef2c8-ee9b-4807-8cdd-b7744f945cf7': 'BU',
 '6df8be14-f7a8-454b-9d0c-3ed566db8673': 'TENN',
 '1d0eee08-3650-4081-bae8-ac7bc3c3cec3': 'CGY',
 '63281d2d-c1c7-4ce2-a0cc-6cc586651f96': 'MIN',
 'd5586d47-9744-408f-b4dd-d11a3f861b10': 'WSH',
 '3b80ba1c-1c0c-4006-b8d2-dcf9fc57c760': 'CAR',
 '20a441c7-0cee-48ce-9d26-c09c94a9e594': 'PHI',
 '3d90c616-020e-4d1c-81c7-b3a2ae66b222': 'SJ',
 '41ca6269-822b-4420-8b71-b0d5eb1b6946': 'Salernitana',
 'd8b93a75-84cc-4b4c-a061-efdf92ba24ae': 'VfL Wolfsburg',
 'e8b191af-2efc-44e5-bbee-6741fb2b9b7c': 'Hellas Verona',
 '1d31bcbc-5e65-4b5e-9cd2-8dbd559927e2': 'Celta de Vigo',
 'd2c15653-e94d-48ad-92f0-d6e92feeb608': 'Nice',
 '2639636c-c3fe-41fd-bba1-669fa20eb08e': 'FC Dallas',
 'b83601c5-8fc1-4d33-836e-eae83bc24237': 'Tottenham',
 'b05d1aa4-58a8-4599-9ea5-65e998db0d49': 'Borussia Dortmund',
 '2cce3512-c3f3-48e5-87d8-98a322d899ee': 'TSG Hoffenheim',
 '639b67ef-1b5a-4d02-9cc4-c41a4d50b88c': 'FSV Mainz 05',
 '3c3ca047-20c0-4585-8454-aa9bee330596': 'Burnley',
 'bb5f95de-889d-41d2-aef2-0b70df30e924': 'Luton Town',
 '555cadc0-a71f-423d-af70-229865735480': 'Everton',
 '4e76167e-8dfb-4ba4-b0b3-b4391b980c7e': 'PSG',
 '2a769f67-40a9-49f3-924b-443dc7e64392': 'Newcastle',
 '64ba152a-62a8-45a5-af39-a88643dadf7b': 'Bilibili Gaming ',
 '2dd237b0-30dc-4987-9f93-32bbc42ecc8c': 'JD Gaming ',
 'e22914e4-6877-48f1-b967-16a2c09129fa': 'KRU ',
 'ff2c361f-2ddd-4cd8-8b25-e59c2505e757': 'FURIA ',
 'b718ef39-628e-4a03-b075-bce5701748ee': 'Giants Gaming ',
 '1324fe30-8584-426e-a62b-1d8f47980e3d': 'CGN Esports ',
 '1256daf7-0501-419a-a26b-d852e86a2760': 'Acend ',
 'e22e6614-3956-49a2-ab87-d1f4e8cd9ec0': 'Pompa ',
 '2e2d6748-7ac7-4393-8c21-04152d38ab4a': 'M80 ',
 'b6962a89-01d2-4a5f-992c-dd2e37d20fe4': 'FLUFFY AIMERS ',
 '88e181c5-dc09-4826-9686-be743405ce45': 'Lynn Vision ',
 'e6d3e707-1662-4eb9-bfa2-edec5a086546': 'Rooster ',
 '4957bf97-6ba1-45b5-86f3-a81435446df1': 'Vantage ',
 '4c4a590b-2f48-4cf5-9df3-4fcd3547d94b': 'Stirlzs Angels ',
 '1e0c1060-b1ba-4ad8-b60d-73ff72bfa543': 'VERTEX ',
 '698fa7e5-738a-495e-a055-f14fa91e2be7': 'ENCE ',
 '8bc8be84-70d8-4b7a-91ef-8e41a08b6a79': 'Heretics Academy ',
 '0fc1c250-5980-4840-af9f-67b479357cb0': 'Meow Gaming Club ',
 '987f333e-f93e-4837-a44f-d43f1e6bf5a2': 'ZennIT ',
 '035a13c8-8aa9-447a-99b9-917ecedc4239': 'LODIS ',
 '4bb9808b-d679-4a63-9755-f1e89861e726': 'Panathinaikos',
 'cccce565-c662-4118-90d8-700bd3da5b70': 'Crvena Zvezda',
 '7a9d17b6-38c3-402a-9f78-4626e1db104d': 'Lyon-Villeurbanne',
 'cb31c28e-6b10-459b-a8e8-123f37715b0d': 'MTL',
 'c3cb471d-2cbd-4cb4-9d57-c8ef7b7d380b': 'BC'}

In [127]:
lines = lines[['stat_value','over_under.appearance_stat.stat', 'over_under.title']]
lines
players = lines['over_under.title'].values
guys = []
for i in players:
    temp = i.split()
    final = temp[0] + ' '+temp[1]
    guys.append(final)
    
guys
lines= lines.rename(columns={'stat_value':'Line','over_under.appearance_stat.stat':'Stat', 'over_under.title':'title'})
lines['Player']= guys
lines['Player'] = lines['Player'].apply(lambda x: unidecode(x).replace('_',' '))

In [128]:
def map_name(x):
    if x is None:
        return None
    if x in first2full:
        return first2full[x]
    elif x.split(': ')[-1] in first2full:
        return x.split(': ')[-1]
    elif x.split()[-1] in first2full:
        return x.split()[-1]
    else:
        return x

lines['Player'] = lines['Player'].apply(lambda x: map_name(x))
lines.Player.unique()

array(['Joel Embiid', 'Tyrese Maxey', 'Tobias Harris', ..., 'J. Milton',
       'J. Wright', 'S. White + R. Keyton'], dtype=object)

In [129]:
league = []
for p in guys:
    if p in p2l:
        league.append(p2l[p])
    elif p.split()[-1] in p2l:
        league.append(p2l[p.split()[-1]])
    else:
        league.append('other')
league[0:5]

['NBA', 'NBA', 'NBA', 'NBA', 'NBA']

In [130]:
guys[1000:1007]

['Jared Goff',
 'Jared Goff',
 'Jared Goff',
 'Jared Goff',
 'Amon-Ra St.',
 'Amon-Ra St.',
 'Amon-Ra St.']

In [131]:
team_id = []
for p in guys:
    if p in p2l:
        team_id.append(p2tm[p])
    elif p.split()[-1] in p2l:
        team_id.append(p2tm[p.split()[-1]])
    else:
        team_id.append('other')
team_id[0:5]

['4dd50e92-0a87-4a6a-bb5d-31c36d88ae72',
 '4dd50e92-0a87-4a6a-bb5d-31c36d88ae72',
 '4dd50e92-0a87-4a6a-bb5d-31c36d88ae72',
 '4dd50e92-0a87-4a6a-bb5d-31c36d88ae72',
 '4dd50e92-0a87-4a6a-bb5d-31c36d88ae72']

In [132]:
lines['League'] = league
lines

,Line,Stat,title,Player,League
0,29.5,points,Joel Embiid Points O/U,Joel Embiid,NBA
1,45.5,pts_rebs_asts,Joel Embiid Pts + Rebs + Asts O/U,Joel Embiid,NBA
2,4.5,assists,Joel Embiid Assists O/U,Joel Embiid,NBA
3,10.5,rebounds,Joel Embiid Rebounds O/U,Joel Embiid,NBA
4,15.5,rebs_asts,Joel Embiid Rebounds + Assists O/U,Joel Embiid,NBA
...,...,...,...,...,...
3355,41.5,pts_rebs_asts,T. Harris + D. Melton Pts + Rebs + Asts O/U,T. Harris + D. Melton,other
3356,3.5,passing_tds,J. Milton III + B. Cook Passing TDs O/U,J. Milton,other
3357,510.5,passing_yds,J. Milton III + B. Cook Passing Yards O/U,J. Milton,other
3358,164.5,rushing_yds,J. Wright + C. Schrader Rushing Yards O/U,J. Wright,other
3359,118.5,receiving_yds,S. White + R. Keyton Receiving Yards O/U,S. White + R. Keyton,other

In [133]:
def map_team(x):
    if x in p2tm:
        return p2tm[x]
    elif p.split()[-1] in p2l:
        return p2tm[p.split()[-1]]
    else:
        return x

lines['team_id'] = lines.Player.apply(lambda x: map_team(x))
lines

,Line,Stat,title,Player,League,team_id
0,29.5,points,Joel Embiid Points O/U,Joel Embiid,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
1,45.5,pts_rebs_asts,Joel Embiid Pts + Rebs + Asts O/U,Joel Embiid,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
2,4.5,assists,Joel Embiid Assists O/U,Joel Embiid,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
3,10.5,rebounds,Joel Embiid Rebounds O/U,Joel Embiid,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
4,15.5,rebs_asts,Joel Embiid Rebounds + Assists O/U,Joel Embiid,NBA,4dd50e92-0a87-4a6a-bb5d-31c36d88ae72
...,...,...,...,...,...,...
3355,41.5,pts_rebs_asts,T. Harris + D. Melton Pts + Rebs + Asts O/U,T. Harris + D. Melton,other,19ecbc41-1201-478c-9937-c339c3963b69
3356,3.5,passing_tds,J. Milton III + B. Cook Passing TDs O/U,J. Milton,other,J. Milton
3357,510.5,passing_yds,J. Milton III + B. Cook Passing Yards O/U,J. Milton,other,J. Milton
3358,164.5,rushing_yds,J. Wright + C. Schrader Rushing Yards O/U,J. Wright,other,J. Wright
3359,118.5,receiving_yds,S. White + R. Keyton Receiving Yards O/U,S. White + R. Keyton,other,47d97fab-ff83-4b75-996a-0643e75e4a21

In [134]:
def map_id(x):
    if x in id2tm:
        return id2tm[x]
    else:
        return x
#lines['team_id'] = lines.team_id.apply(lambda x: map_id(x))

In [135]:
final = pd.merge(lines,matchup, how='left',left_on='team_id',right_on='away_id')
final = final.drop(['Home', 'Away','home_id','away_id'], axis=1)
final2 = pd.merge(final,matchup, how='left',left_on='team_id',right_on='home_id')
final2 = final2.drop(['Home', 'Away','home_id','away_id'], axis=1)
final2['Date'] = final2['Date_x'].fillna(final2['Date_y'])
final2 = final2.drop(['Date_x', 'Date_y'], axis=1)
final2['team_id'] = final2.team_id.apply(lambda x: map_id(x))
final2#.loc[final.Player=='Jimmy Butler']

,Line,Stat,title,Player,League,team_id,Date
0,29.5,points,Joel Embiid Points O/U,Joel Embiid,NBA,PHI,2023-11-10
1,45.5,pts_rebs_asts,Joel Embiid Pts + Rebs + Asts O/U,Joel Embiid,NBA,PHI,2023-11-10
2,4.5,assists,Joel Embiid Assists O/U,Joel Embiid,NBA,PHI,2023-11-10
3,10.5,rebounds,Joel Embiid Rebounds O/U,Joel Embiid,NBA,PHI,2023-11-10
4,15.5,rebs_asts,Joel Embiid Rebounds + Assists O/U,Joel Embiid,NBA,PHI,2023-11-10
...,...,...,...,...,...,...,...
3355,41.5,pts_rebs_asts,T. Harris + D. Melton Pts + Rebs + Asts O/U,T. Harris + D. Melton,other,19ecbc41-1201-478c-9937-c339c3963b69,NaN
3356,3.5,passing_tds,J. Milton III + B. Cook Passing TDs O/U,J. Milton,other,J. Milton,NaN
3357,510.5,passing_yds,J. Milton III + B. Cook Passing Yards O/U,J. Milton,other,J. Milton,NaN
3358,164.5,rushing_yds,J. Wright + C. Schrader Rushing Yards O/U,J. Wright,other,J. Wright,NaN
3359,118.5,receiving_yds,S. White + R. Keyton Receiving Yards O/U,S. White + R. Keyton,other,47d97fab-ff83-4b75-996a-0643e75e4a21,NaN

In [136]:
final2.columns = ['Line', 'Stat', 'title', 'Player', 'League', 'Team', 'Date']

In [137]:
df = final2[['Line', 'Stat', 'Player', 'League', 'Team', 'Date']].copy(deep=True)
df

,Line,Stat,Player,League,Team,Date
0,29.5,points,Joel Embiid,NBA,PHI,2023-11-10
1,45.5,pts_rebs_asts,Joel Embiid,NBA,PHI,2023-11-10
2,4.5,assists,Joel Embiid,NBA,PHI,2023-11-10
3,10.5,rebounds,Joel Embiid,NBA,PHI,2023-11-10
4,15.5,rebs_asts,Joel Embiid,NBA,PHI,2023-11-10
...,...,...,...,...,...,...
3355,41.5,pts_rebs_asts,T. Harris + D. Melton,other,19ecbc41-1201-478c-9937-c339c3963b69,NaN
3356,3.5,passing_tds,J. Milton,other,J. Milton,NaN
3357,510.5,passing_yds,J. Milton,other,J. Milton,NaN
3358,164.5,rushing_yds,J. Wright,other,J. Wright,NaN
3359,118.5,receiving_yds,S. White + R. Keyton,other,47d97fab-ff83-4b75-996a-0643e75e4a21,NaN

In [138]:
df = df.reset_index(drop=True)

In [139]:
df.Stat.unique()

array(['points', 'pts_rebs_asts', 'assists', 'rebounds', 'rebs_asts',
       'pts_asts', 'pts_rebs', 'field_goals_att', 'three_points_att',
       'blocks', 'blks_stls', 'three_points_made', 'personal_fouls',
       'turnovers', 'steals', 'double_doubles', 'passing_yds',
       'rushing_yds', 'passing_att', 'passing_comps', 'passing_ints',
       'passing_and_rushing_yds', 'rushing_att', 'receiving_yds',
       'rush_rec_yds', 'receiving_rec', 'field_goals_made',
       'kicking_points', 'tackles_and_assists', 'tackles', 'passing_tds',
       'fantasy_points', 'sacks', 'rush_rec_tds', 'extra_points_made',
       'shots', 'blocked_shots', 'goals', 'saves', 'shots_attempted',
       'goals_assists', 'shots_on_target', 'goals_against',
       'fouls_against', 'aces', 'double_faults', 'games_won',
       'games_lost', 'games_played', 'strokes', 'kills_in_map_1',
       'kills_in_maps_1_2_3', 'kills_in_map_3', 'kills_in_map_2',
       'fantasy_points_on_map_1', 'fantasy_points_on_maps_1_2_3',
       'assists_in_map_3', 'deaths_in_map_3', 'fantasy_points_on_map_2',
       'deaths_on_maps_1_2_3', 'assists_on_maps_1_2_3',
       'fantasy_points_in_map_3', 'assists_in_map_2', 'assists_on_map_1',
       'deaths_in_map_2', 'deaths_on_map_1', 'map_1_and_2_kills',
       'kills_on_maps_1_2_3', 'headshots_on_maps_1_2',
       'kills_in_maps_1_2', 'finishes', 'significant_strikes',
       'fight_time', 'takedowns', 'total_yds'], dtype=object)

In [140]:
syntax = {
    'pts_rebs_asts': 'PTS+TRB+AST',
    'pts_rebs': 'PTS+TRB',
    'points': 'PTS',
    'free_throws_made': 'FT',
    'fantasy_points': 'Fantasy',
    'rebounds': 'TRB',
    'assists': 'AST',
    'steals': 'STL',
    'blocks': 'BLK',
    'blks_stls': 'BLK+STL',
    'turnovers': 'TO',
    'rebs_asts': 'TRB+AST',
    'pts_asts': 'PTS+AST',
    'three_points_made': '3PM',
    'shots': 'Shots',
    'goals': 'Goals',
    'saves': 'Goalie Saves',
    'clearances': 'Clearances',
    'goals_and_assists': 'Goals and Assists',
    'tackles': 'Tackles',
    'interceptions': 'Interceptions',
    'crosses': 'Crosses',
    'goals_against': 'Goal Against',
    'game_1_and_2_kills': 'MAPS 1-2 Kills',
    'map_1_and_2_kills': 'MAPS 1-2 Kills',
    'kills_in_maps_1_2': 'MAPS 1-2 Kills',
    'Headshots on Maps 1+2': 'MAPS 1-2 Headshots',
    'strokes': 'Strokes',
    'bogeys_or_worse': 'Bogeys or Worse',
    'birdies_or_better': 'Birdies or Better',
    'aces': 'Aces',
    'breakpoints_won': 'Break Points Won',
    'games_won': 'Games Won',
    'games_lost': 'Games Lost',
    'total_games': 'Total Games',
    'double_faults': 'Double Faults',
    'service_games_lost': 'Service Games Lost',
    'Fastest Laps': 'Fastest Laps',
    'position': 'position',
    'passing_yds': 'Pass Yards',
    'rushing_yds': 'Rush Yards',
    'receiving_yds': 'Receiving Yards' ,
    'fantasy_points': 'Hitter Fantasy Score',
    'strikeouts': 'Pitcher Strikeouts',
    'hits_runs_rbis': 'PTS',
    'singles':'Singles',
    'total_bases': 'Total Bases',
    'walks': 'Walks Allowed',
    'hits': 'Hits Allowed',
    'kills_in_map_1' : 'MAPS 1 Kills',
    'kills_in_maps_1_2_3' : 'MAPS 1-3 Kills',
    'kills_in_map_1': 'MAP 1 Kills',
    'kills_in_map_2': 'MAP 2 Kills',
    'kills_in_map_3': 'MAP 3 Kills',
    'fantasy_points_on_maps_1_2_3': 'MAPS 1-3 Fantasy points',
    'fantasy_points_on_map_1': 'MAP 1 Fantasy points',
    'fantasy_points_on_map_2': 'MAP 2 Fantasy points',
    'fantasy_points_on_map_3': 'MAP 3 Fantasy points',
    'deaths_on_maps_1_2_3' : 'MAP 1-3 Deaths',
    'deaths_in_map_2' : 'MAP 2 Deaths',
    'deaths_in_map_3' : 'MAP 3 Deaths',
    'field_goals_att': 'FGA',
    'three_points_att': '3PA',
    'personal_fouls': 'PF',
    'passing_att': 'Pass Attempts',
    'passing_comps': 'Pass Completions',
    'passing_ints': 'Pass Interceptions',
    'passing_and_rushing_yds': 'Pass and Rush Yards',
    'rushing_att': 'Rush Attempts',
    'rush_rec_yds': 'Rush+Rec Yards',
    'receiving_rec': 'Receptions',
    'field_goals_made': 'FGM',
    'kicking_points': 'Kicking Points',
    'tackles_and_assists': 'Tackles+Ast',
    'passing_tds': 'Pass TD',
    'rush_rec_tds': 'Rush+Rec Touchdowns',
    'extra_points_made': 'XP',
    'blocked_shots': 'BLK',
    'shots_attempted': 'Shots',
    'goals_assists': 'Goals and Assists',
    'shots_on_target': 'Shots on Target',
    'fouls_against': 'Fouls Against',
    'assists_on_map_1': 'MAP 1 Assists',
    'assists_in_map_2': 'MAP 2 Assists',
    'fantasy_points_in_map_3': 'MAP 3 Fantasy Points',
    'assists_on_maps_1_2_3': 'MAP 1-3 Assists',
    'assists_in_map_3': 'MAP 3 Assists',
    'kills_on_maps_1_2_3': 'MAP 1-3 Kills',
    'deaths_on_map_1': 'MAP 1 Deaths',
    'headshots_on_maps_1_2': 'MAP 1-2 Headshots',
    'significant_strikes': 'Significant Strikes',
    'fight_time': 'Fight Time',
    'total_yds': 'Total Yards',
    'games_played': 'GP',
                }

In [141]:
df = df.replace(syntax)

In [142]:
df.loc[df['League'] == 'ESPORTS']

      Line            Stat     Player   League              Team        Date
2138   5.5     MAP 1 Kills    Bin+XUN  ESPORTS  Bilibili Gaming   2023-11-11
2139   6.5     MAP 1 Kills  Elk+Yagao  ESPORTS  Bilibili Gaming   2023-11-11
2140  17.0  MAPS 1-3 Kills    Bin+XUN  ESPORTS  Bilibili Gaming   2023-11-11
2141  19.5  MAPS 1-3 Kills  Elk+Yagao  ESPORTS  Bilibili Gaming   2023-11-11
2142   6.5     MAP 3 Kills  Elk+Yagao  ESPORTS  Bilibili Gaming   2023-11-11
...    ...             ...        ...      ...               ...         ...
3165  10.0  MAPS 1-2 Kills      pr1me  ESPORTS     Orbit Anonymo  2023-11-10
3166   8.5  MAPS 1-2 Kills     Savero  ESPORTS     Orbit Anonymo  2023-11-10
3167  10.5  MAPS 1-2 Kills     Roison  ESPORTS     Orbit Anonymo  2023-11-10
3168   2.0  MAPS 1-2 Kills     Czypsy  ESPORTS     Orbit Anonymo  2023-11-10
3169  15.0  MAPS 1-2 Kills    ZAMULEK  ESPORTS     Orbit Anonymo  2023-11-10

[1030 rows x 6 columns]

In [143]:
df.loc[df.Player=='Krimbo']

Empty DataFrame
Columns: [Line, Stat, Player, League, Team, Date]
Index: []

In [144]:
today = dt.date.today()

In [145]:
str(today)

'2023-11-10'

In [146]:
df.columns = [x.lower() for x in df.columns]
df.to_csv(f'Lines/dog/doglines_{today.month}_{today.day}.csv')

In [147]:
df.loc[df.league=='ESPORTS']

      line            stat     player   league              team        date
2138   5.5     MAP 1 Kills    Bin+XUN  ESPORTS  Bilibili Gaming   2023-11-11
2139   6.5     MAP 1 Kills  Elk+Yagao  ESPORTS  Bilibili Gaming   2023-11-11
2140  17.0  MAPS 1-3 Kills    Bin+XUN  ESPORTS  Bilibili Gaming   2023-11-11
2141  19.5  MAPS 1-3 Kills  Elk+Yagao  ESPORTS  Bilibili Gaming   2023-11-11
2142   6.5     MAP 3 Kills  Elk+Yagao  ESPORTS  Bilibili Gaming   2023-11-11
...    ...             ...        ...      ...               ...         ...
3165  10.0  MAPS 1-2 Kills      pr1me  ESPORTS     Orbit Anonymo  2023-11-10
3166   8.5  MAPS 1-2 Kills     Savero  ESPORTS     Orbit Anonymo  2023-11-10
3167  10.5  MAPS 1-2 Kills     Roison  ESPORTS     Orbit Anonymo  2023-11-10
3168   2.0  MAPS 1-2 Kills     Czypsy  ESPORTS     Orbit Anonymo  2023-11-10
3169  15.0  MAPS 1-2 Kills    ZAMULEK  ESPORTS     Orbit Anonymo  2023-11-10

[1030 rows x 6 columns]

In [148]:
df.stat.unique()

array(['PTS', 'PTS+TRB+AST', 'AST', 'TRB', 'TRB+AST', 'PTS+AST',
       'PTS+TRB', 'FGA', '3PA', 'BLK', 'BLK+STL', '3PM', 'PF', 'TO',
       'STL', 'double_doubles', 'Pass Yards', 'Rush Yards',
       'Pass Attempts', 'Pass Completions', 'Pass Interceptions',
       'Pass and Rush Yards', 'Rush Attempts', 'Receiving Yards',
       'Rush+Rec Yards', 'Receptions', 'FGM', 'Kicking Points',
       'Tackles+Ast', 'Tackles', 'Pass TD', 'Hitter Fantasy Score',
       'sacks', 'Rush+Rec Touchdowns', 'XP', 'Shots', 'Goals',
       'Goalie Saves', 'Goals and Assists', 'Shots on Target',
       'Goal Against', 'Fouls Against', 'Aces', 'Double Faults',
       'Games Won', 'Games Lost', 'games_played', 'Strokes',
       'MAP 1 Kills', 'MAPS 1-3 Kills', 'MAP 3 Kills', 'MAP 2 Kills',
       'MAP 1 Fantasy points', 'MAPS 1-3 Fantasy points', 'MAP 3 Assists',
       'MAP 3 Deaths', 'MAP 2 Fantasy points', 'MAP 1-3 Deaths',
       'MAP 1-3 Assists', 'MAP 3 Fantasy Points', 'MAP 2 Assists',
       'MAP 1 Assists', 'MAP 2 Deaths', 'MAP 1 Deaths', 'MAPS 1-2 Kills',
       'MAP 1-3 Kills', 'MAP 1-2 Headshots', 'finishes',
       'Significant Strikes', 'Fight Time', 'takedowns', 'Total Yards'],
      dtype=object)