In [1]:
import torch
import seaborn as sea
import torch.nn.functional as F
import torch.nn as nn
import numpy as np
import pandas as pd
import time
import random
import datetime
import re
import matplotlib.pyplot as plt
import ipywidgets as widgets
from scipy.stats import poisson
%run functions.ipynb
from unidecode import unidecode
plt.rcParams['figure.figsize'] = [13, 7]
pd.set_option("display.precision", 3)

In [1125]:
pd.set_option('display.max_rows', 10)
pd.set_option('display.min_rows', 10)
torch.set_printoptions(sci_mode=False)

In [1129]:
lines = pp_today
p_idx = lines['Player'].unique()
p_idx = np.sort(p_idx)
s_idx = lines['Stat'].unique()
odd = best_odds(lines)
odd['Z'] = (odd['expected']-odd['line'])/odd['line']

In [5]:
pp_lines = pd.read_csv('mlb_lines4_3')
pp_lines

,Unnamed: 0,Player,Team,Line,Stat,League,Date
0,0,Antonino Gallo,Empoli,2.0,Tackles,82,2023-04-03
1,1,Martin Satriano,Lecce,0.5,Shots On Target,82,2023-04-03
2,2,Adama Sanogo,SDSU,8.0,TRB,20,2023-04-03
3,3,Federico Di Francesco,Empoli,0.5,Shots On Target,82,2023-04-03
4,4,Federico Baschirotto,Empoli,4.0,Clearances,82,2023-04-03
...,...,...,...,...,...,...,...
540,540,Tyson Barrie,DAL,0.5,Hits,8,2023-04-03
541,541,Jack McBain,SEA,4.0,Hits,8,2023-04-03
542,542,Jamie Oleksiak,ARI,1.5,Hits,8,2023-04-03
543,543,Liam O'Brien,SEA,3.0,Hits,8,2023-04-03
544,544,Vince Dunn,ARI,1.5,Hits,8,2023-04-03

In [2]:
pd.set_option('display.precision', 2)

In [83]:
unabated = pd.read_csv('mlb_unabated', index_col=0)
unabated = unabated.sort_values(by='Prob')
fullpdf = pd.read_csv('full_mlb', index_col=0)
fullpdf = fullpdf.reset_index(drop=True)

In [84]:
fullpdf = fullpdf.replace('Pitching Strikeouts','Pitcher Strikeouts')
fullpdf.Stat.unique()

array(['Total Bases', 'Total Hits', 'Home Runs', 'Pitcher Strikeouts'],
      dtype=object)

In [85]:
pp_lines.Stat.unique()

array(['Tackles', 'Shots On Target', 'TRB', 'Clearances', 'Shots',
       'BLK+STL', 'TOV', 'PTS', 'PTS+TRB+AST', 'Total Bases',
       'Goalie Saves', 'Hitter Fantasy Score', 'PTS+TRB', 'Strokes',
       'Passes Attempted', 'Goal + Assist', 'Birdies Or Better', 'Runs',
       'Pitcher Strikeouts', 'AST', 'Shots Assisted', '3P', 'Total Games',
       'PTS+AST', 'TRB+AST', 'Fight Time (Mins)', 'Takedowns',
       'Significant Strikes', 'Hits+Runs+RBIS', 'Hitter Strikeouts',
       '1st Inning Hits Allowed', '1st Inning Runs Allowed', 'Rush Yards',
       'Pass Yards', 'Receiving Yards', 'MAPS 1-2 Kills', 'MAP 3 Kills',
       'MAP 3 Headshots', 'Hits'], dtype=object)

In [86]:
jak = fullpdf.loc[fullpdf.Player=='Marcus Semien']
jak

           Player         Stat  Line  Prob  O_price  U_price
36  Marcus Semien    Home Runs   0.5  0.19   386.50   -773.0
37  Marcus Semien  Total Bases   1.5  0.45    80.29   -146.0
38  Marcus Semien   Total Hits   1.5  0.33   184.50   -264.0
39  Marcus Semien   Total Hits   0.5  0.69  -275.00    200.0

In [87]:
fullpdf['pp'] = 0
len(fullpdf)

767

In [88]:
fullpdf.loc[fullpdf.Player=='Elias DÃ­az']

         Player         Stat  Line  Prob  O_price  U_price  pp
373  Elias DÃ­az  Total Bases   0.5  0.54   -140.0    105.0   0
374  Elias DÃ­az   Total Hits   0.5  0.54   -140.0    105.0   0
375  Elias DÃ­az    Home Runs   0.5  0.12    675.0  -2500.0   0

In [89]:
pp_today = pp_lines.copy(deep=True)
pp_today = pp_today.loc[pp_today.League==2]
pp_today['market'] = None
pp_today = pp_today.reset_index(drop=True)

In [92]:
for i in range(len(pp_today)):
#    if i % 50 == 0:
#        print(i,'/',len(fullpdf))
    p = pp_today.Player[i]
    line = pp_today.Line[i]
    stat = pp_today.Stat[i]
    find = fullpdf.loc[(fullpdf.Player == p)]
    find = find.loc[find.Stat==stat]
    find = find.loc[find.Line==line]
    if len(find) != 0:
        pp_today.market[i] = find.Prob.mean()

C:\Users\User\AppData\Local\Temp\ipykernel_13228\3370887669.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pp_today.market[i] = find.Prob.mean()

In [93]:
test = pp_today.dropna()
test.sort_values(by='market')

,Unnamed: 0,Player,Team,Line,Stat,League,Date,market
148,511,Ryne Nelson,SD,4.5,Pitcher Strikeouts,2,2023-04-03,0.46
89,444,Kutter Crawford,PIT,5.5,Pitcher Strikeouts,2,2023-04-03,0.47
48,375,Taijuan Walker,NYY,4.5,Pitcher Strikeouts,2,2023-04-03,0.47
54,381,Aaron Judge,PHI,1.5,Total Bases,2,2023-04-03,0.47
109,472,Nolan Gorman,ATL,0.5,Total Bases,2,2023-04-03,0.48
155,518,James Outman,COL,0.5,Total Bases,2,2023-04-03,0.48
23,330,Dansby Swanson,CIN,1.5,Total Bases,2,2023-04-03,0.48
98,461,JosÃ© BerrÃ­os,KC,4.5,Pitcher Strikeouts,2,2023-04-03,0.49
18,323,Connor Overton,CHC,3.5,Pitcher Strikeouts,2,2023-04-03,0.49
154,517,Michael Grove,COL,4.5,Pitcher Strikeouts,2,2023-04-03,0.49
99,462,Bo Bichette,KC,1.5,Total Bases,2,2023-04-03,0.5
14,284,Michael Kopech,SF,5.5,Pitcher Strikeouts,2,2023-04-03,0.5
144,507,Shea Langeliers,CLE,0.5,Total Bases,2,2023-04-03,0.5
141,504,Esteury Ruiz,CLE,0.5,Total Bases,2,2023-04-03,0.5
118,481,Kyle Bradish,TEX,4.5,Pitcher Strikeouts,2,2023-04-03,0.5
53,380,Nestor Cortes,PHI,6.5,Pitcher Strikeouts,2,2023-04-03,0.5
145,508,Ryan Weathers,ARI,3.5,Pitcher Strikeouts,2,2023-04-03,0.51
125,488,Eric Haase,HOU,0.5,Total Bases,2,2023-04-03,0.51
157,520,Elehuris Montero,LAD,0.5,Total Bases,2,2023-04-03,0.51
96,459,Brady Singer,TOR,4.5,Pitcher Strikeouts,2,2023-04-03,0.51
162,525,Ezequiel Tovar,LAD,0.5,Total Bases,2,2023-04-03,0.52
74,401,Trevor Williams,TB,3.5,Pitcher Strikeouts,2,2023-04-03,0.52
65,392,Kyle Schwarber,NYY,0.5,Total Bases,2,2023-04-03,0.52
12,280,David Villar,CWS,0.5,Total Bases,2,2023-04-03,0.52
121,484,RamÃ³n UrÃ­as,TEX,0.5,Total Bases,2,2023-04-03,0.53
87,442,Jason Delay,BOS,0.5,Total Bases,2,2023-04-03,0.53
142,505,Jace Peterson,CLE,0.5,Total Bases,2,2023-04-03,0.53
78,411,Victor Robles,TB,0.5,Total Bases,2,2023-04-03,0.53
75,408,Jose Siri,WSH,0.5,Total Bases,2,2023-04-03,0.53
59,386,Bryson Stott,NYY,0.5,Total Bases,2,2023-04-03,0.53
160,523,Elias DÃ­az,LAD,0.5,Total Bases,2,2023-04-03,0.54
126,489,Spencer Torkelson,HOU,0.5,Total Bases,2,2023-04-03,0.54
84,439,Jack Suwinski,BOS,0.5,Total Bases,2,2023-04-03,0.54
108,471,Dylan Carlson,ATL,0.5,Total Bases,2,2023-04-03,0.54
3,69,Carlos Carrasco,MIL,4.5,Pitcher Strikeouts,2,2023-04-03,0.54

In [102]:
test[(test.market > 0.525) | (test.market < 0.475)]

,Unnamed: 0,Player,Team,Line,Stat,League,Date,market
3,69,Carlos Carrasco,MIL,4.5,Pitcher Strikeouts,2,2023-04-03,0.54
48,375,Taijuan Walker,NYY,4.5,Pitcher Strikeouts,2,2023-04-03,0.47
54,381,Aaron Judge,PHI,1.5,Total Bases,2,2023-04-03,0.47
59,386,Bryson Stott,NYY,0.5,Total Bases,2,2023-04-03,0.53
75,408,Jose Siri,WSH,0.5,Total Bases,2,2023-04-03,0.53
78,411,Victor Robles,TB,0.5,Total Bases,2,2023-04-03,0.53
84,439,Jack Suwinski,BOS,0.5,Total Bases,2,2023-04-03,0.54
87,442,Jason Delay,BOS,0.5,Total Bases,2,2023-04-03,0.53
89,444,Kutter Crawford,PIT,5.5,Pitcher Strikeouts,2,2023-04-03,0.47
108,471,Dylan Carlson,ATL,0.5,Total Bases,2,2023-04-03,0.54
121,484,RamÃ³n UrÃ­as,TEX,0.5,Total Bases,2,2023-04-03,0.53
126,489,Spencer Torkelson,HOU,0.5,Total Bases,2,2023-04-03,0.54
142,505,Jace Peterson,CLE,0.5,Total Bases,2,2023-04-03,0.53
148,511,Ryne Nelson,SD,4.5,Pitcher Strikeouts,2,2023-04-03,0.46
160,523,Elias DÃ­az,LAD,0.5,Total Bases,2,2023-04-03,0.54

In [70]:
fullpdf.loc[fullpdf.pp!=0].sort_values(by='Prob')

Empty DataFrame
Columns: [Player, Stat, Line, Prob, O_price, U_price, pp]
Index: []

In [71]:
unabated

           player  points  price   side       stat    book  Prob  Opp Team
0    Adam Frazier     0.5   1000   over  Home Runs  BetMGM  0.09  TEX  BAL
0    Anthony Kemp     0.5   1000   over  Home Runs  BetMGM  0.09  OAK  CLE
0     Jason Delay     0.5    950   over  Home Runs  BetMGM  0.10  BOS  PIT
0   Victor Robles     0.5    950   over  Home Runs  BetMGM  0.10  WAS   TB
0    Esteury Ruiz     0.5    950   over  Home Runs  BetMGM  0.10  OAK  CLE
..            ...     ...    ...    ...        ...     ...   ...  ...  ...
0   Victor Robles     0.5 -10000  under  Home Runs  BetMGM  0.99  WAS   TB
0    Adam Frazier     0.5 -10000  under  Home Runs  BetMGM  0.99  TEX  BAL
0     Jason Delay     0.5 -10000  under  Home Runs  BetMGM  0.99  BOS  PIT
0    Anthony Kemp     0.5 -10000  under  Home Runs  BetMGM  0.99  OAK  CLE
0    Esteury Ruiz     0.5 -10000  under  Home Runs  BetMGM  0.99  OAK  CLE

[4844 rows x 9 columns]

In [72]:
unabated.loc[unabated.player=='Elias DÃ­az']

       player  points  price   side         stat    book  Prob  Opp Team
0  Elias DÃ­az     0.5    675   over    Home Runs  BetMGM  0.13  LAD  COL
0  Elias DÃ­az     0.5    105  under   Total Hits  BetMGM  0.49  LAD  COL
0  Elias DÃ­az     0.5    105  under  Total Bases  BetMGM  0.49  LAD  COL
0  Elias DÃ­az     0.5   -140   over   Total Hits  BetMGM  0.58  LAD  COL
0  Elias DÃ­az     0.5   -140   over  Total Bases  BetMGM  0.58  LAD  COL
0  Elias DÃ­az     0.5  -2500  under    Home Runs  BetMGM  0.96  LAD  COL

In [ ]:
pts